<?php

namespace App\Http\Controllers\FixedAsset;

use App\Http\Controllers\Controller;
use App\Models\FixedAsset\Asset;
use Illuminate\Http\Request;

class AssetController extends Controller
{
    public function index()
    {
        $db = session()->get('database');
        // $kdcab = session()->get();
        $asetList = Asset::db($db)->listAsset();
        return view('fixedasset.aset.index', compact('asetList'));
    }

    public function barcode(Request $request)
    {
        $db = session()->get('database');
        $aset = Asset::db($db)->getAssetById('001', $request->barcode);
        return view('fixedasset.aset.barcode', compact('aset'));
    }

    public function indexDelete()
    {

    }
    //
    public function getLastNoref()
    {
        $noref = Asset::db('live')->lastNoref('001');
        return $noref;
    }

    public function getBarcode($kdid = '00000')
    {
        $barcode = Asset::db('live')->getBarcode('001', '0000');
        return $barcode;
    }

    public function listApproval()
    {

    }

    public function listApprovalByID($barcode)
    {
        $sql = "SELECT RETSITO.MERK MERK,RETSITO.NOAC,RETSITO.NOREF,RETSITO.NOID,RETSITO.TCD,RETSITO.KDID,RETSITO.KET,RETSITO.TGLVAL,RETSITO.JKWKT,RETSITO.KDCAB,RETSITO.NIK,RETSITO.DEPT,RETSITO.NILAI,RETSITO.SISAAMOR,TBLTCD.TNM,X.KETERANGAN KET_KDID,RETSITO.STATUS,RETSITO.STSSI,RETSITO.FILE_UPLOAD,AMOR_PENDING,SISAAMOR_SBL,AMOR_PENDINGSBL,KONDISI.KONDISI,KONDISI.ID,DEPARTMENT.DESCRIPTION NMDEPARTMENT,KRWPNJM.NAMA_LENGKAP,RETSITO.ALASAN,RETSITO.QRCODE,RETSITO.USRID,RETSITO.CCY,CURRENCY.DESCRIPTION MATA_UANG,RETSITO.TGLBEBAN,RETSITO.JENIS_HARTA,Y.KETERANGAN KET_JENIS_HARTA,RETSITO.DUPD, RETSITO.NLPERUBAHAN, RETSITO.NOGL_BANK, RETSITO.KD_FILTER, Z.KETERANGAN KET_JENIS_FILTER
		FROM RETSITO INNER JOIN TBLTCD ON RETSITO.TCD = TBLTCD.TRN_CODE
		LEFT OUTER JOIN (SELECT * FROM SANDI_BI WHERE KD_BI ='SI') X ON RETSITO.KDID = X.KD_SANDI
		LEFT OUTER JOIN (SELECT * FROM SANDI_BI WHERE KD_BI ='SI') Y ON RETSITO.JENIS_HARTA = Y.KD_SANDI
		LEFT OUTER JOIN (SELECT * FROM SANDI_BI WHERE KD_BI ='KF') Z ON RETSITO.KD_FILTER = Y.KD_SANDI
		LEFT OUTER JOIN KONDISI ON RETSITO.STSSI = KONDISI.ID
		LEFT OUTER JOIN DEPARTMENT ON RETSITO.DEPT = DEPARTMENT.DEPTCODE
		LEFT OUTER JOIN KRWPNJM ON RETSITO.NIK = KRWPNJM.NIK
		INNER JOIN CURRENCY ON RETSITO.CCY = CURRENCY.CURRENCY
		WHERE RETSITO.QRCODE = '" . $barcode . "'";
        $que = $this->db->select($sql);
        return $que[0];
    }

    public function listAsset()
    {
        $sql = "SELECT RETSIT.MERK,RETSIT.NOREF,RETSIT.NOID,RETSIT.TCD,RETSIT.KDID,RETSIT.KET,RETSIT.TGLVAL,RETSIT.JKWKT,RETSIT.KDCAB,RETSIT.NIK,RETSIT.DEPT,RETSIT.NILAI,RETSIT.SISAAMOR,TBLTCD.TNM,SANDI_BI.KETERANGAN,SHDBLC.ALIASNM CNM,RETSIT.STATUS,RETSIT.STSSI,RETSIT.FILE_UPLOAD,AMOR_PENDING,SISAAMOR_SBL,AMOR_PENDINGSBL,KONDISI.KONDISI,KONDISI.ID,DEPARTMENT.DESCRIPTION,KRWPNJM.NAMA_LENGKAP,RETSIT.QRCODE,RETSIT.USRID,TBLTCD.TRNKOREKSI, RETSIT.NLPERUBAHAN
		FROM RETSIT INNER JOIN TBLTCD ON RETSIT.TCD = TBLTCD.TRN_CODE
		LEFT OUTER JOIN SANDI_BI ON RETSIT.KDID = SANDI_BI.KD_SANDI AND KD_BI = 'SI'
		LEFT OUTER JOIN SHDBLC ON RETSIT.NOAC = SHDBLC.NOAC
		LEFT OUTER JOIN KONDISI ON RETSIT.STSSI = KONDISI.ID
		LEFT OUTER JOIN DEPARTMENT ON RETSIT.DEPT = DEPARTMENT.DEPTCODE
		LEFT OUTER JOIN KRWPNJM ON RETSIT.NIK = KRWPNJM.NIK
		WHERE RETSIT.KDCAB = '" . $this->kdcab . "' and RETSIT.STATUS <> '4' ";
        $que = $this->db->select($sql);
        return $que;
    }

    public function listAssetDel()
    {
        $sql = "SELECT RETSIT.NOREF, KRWPNJM.NAMA_LENGKAP, RETSIT.NOID, RETSIT.KET, RETSIT.MERK, RETSIT.NILAI, KONDISI.KONDISI, RETSIT.QRCODE QRCODE, TBLTCD.TRNKOREKSI, 
                RETSIT.TGLVAL, SANDI_BI.KETERANGAN as TYPE, RETSIT.SISAAMOR, Y.KETERANGAN NMJENISHARTA, CABANG.NM_CABANG, RETSIT.JKWKT, RETSIT.PRINT, 
                RETSIT.SISAAMOR_SBL, RETSIT.SISAAMOR_YBF, RETSIT.NILAIAMOR_YBF, RETSITHIS.DUPD
                FROM RETSIT LEFT OUTER JOIN KONDISI ON RETSIT.STSSI = KONDISI.ID 
                            LEFT OUTER JOIN SANDI_BI ON RETSIT.KDID = SANDI_BI.KD_SANDI AND KD_BI = 'SI' 
                            LEFT OUTER JOIN (SELECT * FROM SANDI_BI WHERE KD_BI = 'SI') Y ON RETSIT.JENIS_HARTA = Y.KD_SANDI 
                            INNER JOIN KRWPNJM ON RETSIT.NIK = KRWPNJM.NIK 
                            INNER JOIN TBLTCD ON RETSIT.TCD = TBLTCD.TRN_CODE 
                            INNER JOIN CABANG ON RETSIT.KDCAB = CABANG .KD_CABANG 
                            INNER JOIN RETSITHIS ON RETSIT.NOREF = RETSITHIS.NOREF AND RETSIT.NOID = RETSITHIS.NOID
                WHERE retsit.status = '4' AND TBLTCD.TRNKOREKSI LIKE 'F' AND RETSIT.JENIS_HARTA LIKE '%' AND RETSIT.KDID LIKE '%' AND RETSIT.NIK LIKE '%' 
                ORDER BY QRCODE DESC";
        $que = $this->db->select($sql);
        return $que;
    }

    public function getAssetByID($barcode)
    {
        $sql = "SELECT RETSIT.MERK MERK,RETSIT.NOREF,RETSIT.NOID,RETSIT.TCD,RETSIT.KDID,RETSIT.KET,RETSIT.TGLVAL,RETSIT.JKWKT,RETSIT.KDCAB,RETSIT.NIK,RETSIT.DEPT,RETSIT.NILAI,RETSIT.SISAAMOR,TBLTCD.TNM,X.KETERANGAN KET_KDID,RETSIT.STATUS,RETSIT.STSSI,RETSIT.FILE_UPLOAD,AMOR_PENDING,SISAAMOR_SBL,AMOR_PENDINGSBL,KONDISI.KONDISI,KONDISI.ID,DEPARTMENT.DESCRIPTION NMDEPARTMENT,KRWPNJM.NAMA_LENGKAP,RETSIT.QRCODE,RETSIT.USRID,RETSIT.CCY,CURRENCY.DESCRIPTION MATA_UANG,RETSIT.TGLBEBAN,RETSIT.JENIS_HARTA,Y.KETERANGAN KET_JENIS_HARTA,CABANG.NM_CABANG, RETSIT.NLPERUBAHAN, RETSIT.DUPD, RETSIT.OTR, RETSIT.DOTR, RETSIT.NOGL_BANK, RETSIT.KD_FILTER
		FROM RETSIT INNER JOIN TBLTCD ON RETSIT.TCD = TBLTCD.TRN_CODE
		LEFT OUTER JOIN (SELECT * FROM SANDI_BI WHERE KD_BI ='SI') X ON RETSIT.KDID = X.KD_SANDI
		LEFT OUTER JOIN (SELECT * FROM SANDI_BI WHERE KD_BI ='SI') Y ON RETSIT.JENIS_HARTA = Y.KD_SANDI
		LEFT OUTER JOIN KONDISI ON RETSIT.STSSI = KONDISI.ID
		LEFT OUTER JOIN DEPARTMENT ON RETSIT.DEPT = DEPARTMENT.DEPTCODE
		LEFT OUTER JOIN KRWPNJM ON RETSIT.NIK = KRWPNJM.NIK
		INNER JOIN CURRENCY ON RETSIT.CCY = CURRENCY.CURRENCY
		INNER JOIN CABANG ON RETSIT.KDCAB = CABANG.KD_CABANG
		WHERE RETSIT.KDCAB = '" . $this->kdcab . "' and RETSIT.QRCODE = '" . $barcode . "' and RETSIT.STATUS <> '4' ";
        $que = $this->db->select($sql);
        if ($que) {
            return $que[0];
        } else {
            return;
        }
    }

    public function listBarcode($id)
    {
        $sql = "SELECT RETSIT.NOREF,NOID,RETSIT.KET,RETSIT.MERK AS KETHD,RETSIT.NILAI,KONDISI.KONDISI,RETSIT.QRCODE QRCODE,RETSIT.TGLVAL,SANDI_BI.KETERANGAN as TYPE
		FROM RETSIT LEFT OUTER JOIN KONDISI ON RETSIT.STSSI = KONDISI.ID
		LEFT OUTER JOIN SANDI_BI ON RETSIT.KDID = SANDI_BI.KD_SANDI AND KD_BI = 'SI'
		WHERE RETSIT.KDCAB = '" . $this->kdcab . "' and retsit.status = '1' and retsit.stssi = 'OK' AND RETSIT.PRINT = '$id'
		ORDER BY QRCODE DESC";
        $que = $this->db->select($sql);
        return $que;
    }
}
